version: '3.8'

services:
  db:
    image: mysql
    platform: linux/amd64 #mac環境で必須なことがあるらしい
    env_file: .env
    container_name: v_kara_db
    build:
      context: ./db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 
    # command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
  
  api:
    build: 
      context: ./t0016Go
    container_name: v_kara_api
    env_file: .env
    stdin_open: true
    tty: true
    volumes:
      - ./t0016Go:/api/src
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  app:
    build:
      context: ./t0016Next
    container_name: v_kara_app
    stdin_open: true
    tty: true
    volumes:
      - ./t0016Next/myapp:/app/src
    # depends_on:
    #    - "api" 
    ports:
      - "80:80"

# INSERT INTO karaoke_lists 
# (movie_url,  sing_start, song_name, karaoke_list_inputter_id) 
# VALUE
# ('www.youtube.com/watch?v=5WzeYsoGCZc', '00:08:07', 'aaa', 1);